### ISSUE TITLE
ember-fetch + fastboot + ember-data sadness

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/ember-fetch#38]
fastboot and fetch share the same extension point in ember-data, and today they do not work together.

Long-term, I suspect fastboot should provide and XMLHTTPRequest global, and a fetch global. That way it doesn't interfere in high level code, and would also "just work" with things like pretender/mirage.

**Comment by 0xadada** [comment]
I'm running into this exact problem now. My app uses fastboot, ember-data, ember-fetch, and I'm in the process of removing jquery and everything is working, _except_ fastboot fetches with the following error:

```
Error while processing route: index Cannot read property 'catch' of undefined TypeError: Cannot read property 'catch' of undefined
    at Class.ajax (/Users/ron/mirai-audio/mir/tmp/broccoli_merge_trees-output_path-IEMm2qLU.tmp/assets/addon-tree-output/ember-fetch/mixins/adapter-fetch.js:200:1)
    at Class.findAll (/Users/ron/mirai-audio/mir/tmp/broccoli_merge_trees-output_path-IEMm2qLU.tmp/assets/addon-tree-output/modules/ember-data/adapters/rest.js:473:1)
    at _findAll (/Users/ron/mirai-audio/mir/tmp/broccoli_merge_trees-output_path-IEMm2qLU.tmp/assets/addon-tree-output/modules/ember-data/-private.js:8501:1)
    at Class._fetchAll (/Users/ron/mirai-audio/mir/tmp/broccoli_merge_trees-output_path-IEMm2qLU.tmp/assets/addon-tree-output/modules/ember-data/-private.js:10967:1)
    at Class.findAll (/Users/ron/mirai-audio/mir/tmp/broccoli_merge_trees-output_path-IEMm2qLU.tmp/assets/addon-tree-output/modules/ember-data/-private.js:10938:1)
    at Class.model (/Users/ron/mirai-audio/mir/tmp/broccoli_merge_trees-output_path-IEMm2qLU.tmp/assets/mir/routes/index.js:23:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nlfurniss** [comment]
@0xadada you can get around this issue with [these instructions](https://github.com/ember-cli/ember-fetch/blob/master/README.md#use-with-fastboot).

**Comment by 0xadada** [comment]
@nlfurniss unfortunately not because I've also removed jQuery in my app as a dependency, and the `then().catch()` semantics of ember fetch don't yet align with fastboot expectations.

**Comment by nlfurniss** [comment]
Did you try adding the initializer to override fastboot per the README?

**Comment by Duder-onomy** [comment]
I also ran into an identical issue with `ember-data` `ember-fetch` `ember-cli-fastboot` and `ember-simple-auth`

Ember-fetch's ajaxOption's does not call super, which results in any other extensions of your application adapter not having the opportunity to set headers or anything like that. The current implementation of ember-fetch's ajaxOptions do not allow [this](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/data-adapter-mixin.js#L77) to run.

This breaks `ember-simple-auth` because the `ember-simple-auth`'s adapter mixin needs to set your auth header. 

My workaround is to manually set the headers I need after ember-fetch has run:
```javascript
  ajaxOptions(...args) {
    const options = this._super(...args);

    get(this, 'session').authorize(get(this, 'authorizer'), (headerName, headerValue) => {
      options.headers[headerName] = headerValue;
    });

    return options;
  },
```

**Comment by 0xadada** [comment]
@nlfurniss that worked! I hadn't taken that step, because it wasn't in the README back when i first switched to `ember-fetch`. Thanks!

**Comment by tchak** [comment]
I just want to mention that we are moving fetch support to Ember Data itself : https://github.com/emberjs/data/pull/5386

**Comment by ehubbell** [comment]
@Duder-onomy I'm running into the same issue (using the same libraries) as you explain above. Curious, would you mind elaborating on where and how you manually set those headers?

**Comment by Duder-onomy** [comment]
@ehubbell Totally. 

The latest ember-simple-auth has deprecated authorizers... So I had to change some things a few weeks ago.  Now that `ajaxOptions` hook I pasted above looks a little different.

Here is my entire application adapter:
```javascript
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';
import AdapterFetch from 'ember-fetch/mixins/adapter-fetch';
import { get } from '@ember/object';
import { inject as service } from '@ember/service';
import config from '../config/environment';

const { JSONAPIAdapter } = DS;

export default JSONAPIAdapter.extend(DataAdapterMixin, AdapterFetch, {
  session: service(),

  authorizer: 'authorizer:application',

  coalesceFindRequests: true,

  host: config.APP.apiBase,
  namespace: config.APP.apiNamespace,

  headers: {
    'X-Requested-with': 'XMLHttpRequest',
  },

  ajaxOptions(...args) {
    const options = this._super(...args);
    const accessToken = get(this, 'session.data.authenticated.access_token');

    options.headers['X-Access-Token'] = accessToken;

    options.headers['Content-Type'] = 'application/vnd.api+json';

    return options;
  },
});
```

Hope that helps.

**Comment by ehubbell** [comment]
@Duder-onomy Thanks for the help! Turns out I had my `fastboot` directory inside my `app` directory hence the issues my `ajax` service. Once I fixed that and installed something similar to your code above, everything's working.

**Comment by mdbiscan** [comment]
I have this same problem, but I don't understand this part of the README:
```
...you must add an initializer to the **consuming app's fastboot directory** that overrides the one Fastboot utilizes to inject its own ajax...
```
I have not seen such a directory in my app? Does the Fastboot App Server need any special configuration?

**Comment by nlfurniss** [comment]
@mdbiscan yes, [here is an example](https://github.com/nlfurniss/ember-fastboot-test-app/blob/master/fastboot/initializers/ajax.js)

**Comment by mdbiscan** [comment]
@nlfurniss sorry, hit delete by accident.

I was able to do that, but I get this error: 

`Error: The adapter rejected the commit because it was invalid`

Trying to debug now, but does this also require headers to be taken care of in `ajaxOptions`? I'm using the headers computed.

**Comment by mdbiscan** [comment]
One of my issues is needing to pass HTTPOnly cookies. In my adapter, I had to add this:

```
  headers: computed('csrftoken', 'fastboot', function() {
    const csrftoken = this.get('csrftoken');
    const fastboot = this.get('fastboot');
    const headers = {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      'X-CSRFToken': csrftoken,
    };

    // Pass httpOnly cookies when in fastboot
    if(fastboot.isFastBoot) {
      headers['Cookie'] = fastboot.get('request.headers.cookie');
    }

    return headers
  }),
```

**Comment by 0xadada** [comment]
# Solutions!

@stefanpenner 
Here is how I've finally solved the problem, i'm also using `ember-data` with `ember-fetch` running in an `ember-cli-fastboot` with `ember-simple-auth` and have removed `jQuery` as a dependency.

> Here is my entire application adapter:

re: ☝️ @Duder-onomy your  application adapter uses authorizers, which has since become a [deprecated pattern in ember-simple-auth](https://github.com/simplabs/ember-simple-auth/#authorizers).

> Authorizers and the session service's authorize method are deprecated and will be removed from Ember Simple Auth 2.0. The concept seemed like a good idea in the early days of Ember Simple Auth, but proved to provide limited value for the added complexity. To replace authorizers in an application, simply get the session data from the session service and inject it where needed.

When used with `ember-fetch` the `ajaOptions` doesn't work well, and the `authorize` method will not be called. The `headers` computed property must be used instead. Here is my application adapter using `ember-fetch`:

```js
// app/adapters/application.js
import JSONAPIAdapter from 'ember-data/adapters/json-api';
import AdapterFetchMixin from 'ember-fetch/mixins/adapter-fetch';
import config from 'mir/config/environment';
import { computed } from '@ember/object';
import { inject as service } from '@ember/service';

export default JSONAPIAdapter.extend(AdapterFetchMixin, {
  session: service(),

  host: config.DS.host,
  namespace: config.DS.namespace,

  headers: computed('session.data.authenticated.token', function() {
    const headers = {};
    headers['Content-Type'] = 'application/vnd.api+json';
    if (this.session.isAuthenticated) {
      const token = this.session.data.authenticated['access_token'];
      headers['Authorization'] = `Bearer ${token}`;
    }
    return headers;
  })
});
```

I also followed the [ember-fetch README](https://github.com/ember-cli/ember-fetch/blob/master/README.md#ajax-service), to disable the ajax instance initializer on fastboot:
```js
// fastboot/initializers/ajax.js
export default {
  name: 'ajax-service',
  initialize() {
    // noop
    // This is to override Fastboot's initializer which prevents ember-fetch from working
    // https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/fastboot/initializers/ajax.js
  }
}
```

One of the nice benefits of this approach is that it helps paves the way to removing jQuery, especially with `$.ajax` no longer used by `ember-data`.

**Comment by snewcomer** [comment]
Note on setting `ajaxOptions`.  I would follow what was recommended in the below .  Also, `headers` as a computed may be another source of a memory leak.  Changing to a static getter e.g. `get header` may have fixed leaking an internal part of Ember.

Just sending out a message in a bottle in case anybody picks it up.  Your app may be slightly different, so make sure you have a memory leak before changing from a computed to `getter`.

Ref - https://github.com/emberjs/data/issues/5061#issuecomment-390778103

**Comment by snewcomer** [comment]
@allthesignals ref issue for container memory leaks
