### ISSUE TITLE
"Invalid Mapping" from ember-cli-uglify on build

### ISSUE THREAD

**Issue by chrismllr** [stefanpenner/ember-fetch#9]
Getting this error on minify from ember-cli-uglify on build...

```
File: assets/vendor.js
Invalid mapping: {"generated":{"line":111536,"column":-5},"source":"vendor/whatwg-fetch/fetch.js","original":{"line":1,"column":0},"name":null}
Error: Invalid mapping: {"generated":{"line":111536,"column":-5},"source":"vendor/whatwg-fetch/fetch.js","original":{"line":1,"column":0},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:272:15)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:102:12)
    at /Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:74:19
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-consumer.js:473:10)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js:50:26)
    at Context.SourceMap (/Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/sourcemap.js:59:52)
    at Object.exports.minify (/Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:111:38)
    at UglifyWriter.processFile (/Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:99:27)
    at /Users/chrism/myapp/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/index.js:46:14
```

This may be an issue in the actual github-fetch polyfill ?

Ember CLI v1.13.7
Ember v1.13.10

**Comment by chrismllr** [comment]
I apologize, I found this issue elsewhere, it is related to ember-cli-uglify. Closing this issue.
https://github.com/ember-cli/ember-cli-uglify/issues/4
